#
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.22
    hostname: mqtt-broker
    read_only: true
    container_name: mqtt-broker
    user: "1883:1883"
    security_opt:
      - no-new-privileges
    volumes:
      - ./configs/mosquitto/config:/mosquitto/config
    networks:
      - app_network
  
  dlstreamer-pipeline-server:
    image: ${DOCKER_REGISTRY}${DLSTREAMER_PIPELINE_SERVER_IMAGE}
    hostname: dlstreamer-pipeline-server
    container_name: dlstreamer-pipeline-server
    read_only: true
    security_opt:
      - no-new-privileges
    privileged: false
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - mediamtx
    environment:
      AppName: "DLStreamerPipelineServer"
      ENABLE_WEBRTC: true
      WEBRTC_SIGNALING_SERVER: http://mediamtx:8889
      ENABLE_RTSP: true
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}${no_proxy:+,}${HOST_IP}${HOST_IP:+,}${RTSP_CAMERA_IP}${RTSP_CAMERA_IP:+,}otel-collector,mediamtx,model_registry,mqtt-broker
      NO_PROXY: ${no_proxy}${no_proxy:+,}${HOST_IP}${HOST_IP:+,}${RTSP_CAMERA_IP}${RTSP_CAMERA_IP:+,}otel-collector,mediamtx,model_registry,mqtt-broker
      GST_DEBUG: "1"
      REST_SERVER_PORT: ${REST_SERVER_PORT}
      S3_STORAGE_HOST: ${MR_MINIO_HOSTNAME:-"minio-server"}
      S3_STORAGE_PORT: ${MR_MINIO_SERVER_PORT:-9000}
      S3_STORAGE_USER: ${MR_MINIO_ACCESS_KEY:-""}
      S3_STORAGE_PASS: ${MR_MINIO_SECRET_KEY:-""}
      SERVICE_NAME: "dlstreamer-pipeline-server"
      ENABLE_OPEN_TELEMETRY: true
      OTEL_COLLECTOR_HOST: ${OTEL_COLLECTOR_HOST}
      OTEL_COLLECTOR_PORT: ${OTEL_COLLECTOR_PORT}
      OTEL_EXPORT_INTERVAL_MILLIS: ${OTEL_EXPORT_INTERVAL_MILLIS}
      OPCUA_SERVER_IP: ${OPCUA_SERVER_IP:-"ia-opcua-server"}
      OPCUA_SERVER_PORT: ${OPCUA_SERVER_PORT:-4840}
      OPCUA_SERVER_USERNAME: ${OPCUA_SERVER_USERNAME:-""}
      OPCUA_SERVER_PASSWORD: ${OPCUA_SERVER_PASSWORD:-""}
      # Model Registry Microservice
      MR_URL: ${MR_URL:-""}
      MR_SAVED_MODELS_DIR: ${MR_URL:-""}
      MR_REQUEST_TIMEOUT: ${MR_REQUEST_TIMEOUT:-""}
      MR_VERIFY_CERT: ${MR_VERIFY_CERT:-""}
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883
    volumes:
      - vol_pipeline_root:/var/cache/pipeline_root:uid=1999,gid=1999
      - "/run/udev:/run/udev:ro"
      - "${DRI_MOUNT_PATH:-/dev/null}:/dev/dri"
      - "${ACCEL_MOUNT_PATH:-/dev/null}:/dev/accel"
      - "/tmp:/tmp"
      - "./configs/pid/models/object_detection:/home/pipeline-server/object_detection"
      - "./configs/pid/videos:/home/pipeline-server/resources/externalvideos"
      - ./configs/pid/config.json:/home/pipeline-server/config.json
    group_add:
      # render group ID for ubuntu 20.04 host OS
      - "109"
      # render group ID for ubuntu 22.04 host OS
      - "110"
      # render group ID for ubuntu 24.04 host OS
      - "992"
    device_cgroup_rules:
      # Default run - device-cgroup-rule='c 189:* rmw'
      # Selective rules can be applied for deployment
      - "c 189:* rmw"
      - "c 209:* rmw"
      - "a 189:* rwm"
    devices:
      # Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
      # accel - NPU
      # Selective mount can be done for deployment as mounting whole /dev is not recommended
      - "${DRI_MOUNT_PATH:-/dev/null}:/dev/dri"
      - "${ACCEL_MOUNT_PATH:-/dev/null}:/dev/accel"

  mediamtx:
    image: bluenviron/mediamtx:1.21.0
    container_name: mediamtx
    restart: unless-stopped
    read_only: true
    user: "1000:1000"
    security_opt:
      - no-new-privileges
    environment:
      - MTX_LOGLEVEL=info
      - MTX_RTSP=yes
      - MTX_RTMP=no
      - MTX_HLS=no
      - NO_PROXY=mediamtx,coturn,${no_proxy},${HOST_IP}
      - no_proxy=mediamtx,coturn,${no_proxy},${HOST_IP}
      # Path settings for cam1
      - MTX_AUTHINTERNALUSERS_PUBLISHER_USER=publisher
      - MTX_AUTHINTERNALUSERS_PUBLISHER_PASS=pubpass
      - MTX_AUTHINTERNALUSERS_PUBLISHER_PERMISSIONS_0=publish
      - MTX_AUTHINTERNALUSERS_PUBLISHER_PATHS_0=cam1
      - MTX_AUTHINTERNALUSERS_VIEWER_USER=viewer
      - MTX_AUTHINTERNALUSERS_VIEWER_PASS=viewpass
      - MTX_AUTHINTERNALUSERS_VIEWER_PERMISSIONS_0=read
      - MTX_AUTHINTERNALUSERS_VIEWER_PATHS_0=cam1
      - MTX_WEBRTCTRACKGATHERTIMEOUT=20s
      - MTX_WEBRTC=yes
      - MTX_WEBRTCICESERVERS2_0_URL=turn:${HOST_IP}:${COTURN_UDP_PORT}
      - MTX_WEBRTCICESERVERS2_0_USERNAME=${MTX_WEBRTCICESERVERS2_0_USERNAME}
      - MTX_WEBRTCICESERVERS2_0_PASSWORD=${MTX_WEBRTCICESERVERS2_0_PASSWORD}
    networks:
    - app_network

  coturn:
    image: coturn/coturn:4.18.0-alpine
    container_name: coturn
    read_only: true
    user: "1000:1000"
    security_opt:
      - no-new-privileges
    ports:
      - "${COTURN_UDP_PORT}:3478"
      - "${COTURN_UDP_PORT}:3478/udp"
    command: ["-v"]  # Verbose mode for logging
    networks:
    - app_network

  ase-chromadb:
    image: chromadb/chroma:1.5.9
    hostname: ase-chromadb
    container_name: ase-chromadb
    user: "1000:1000"
    read_only: true
    security_opt:
      - no-new-privileges
    networks: 
      - app_network
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    volumes:
      - chroma_data:/tmp
      - chroma_data:/data
      - chroma_data:/tmp

  aig-server:
    image: ${DOCKER_REGISTRY}${AIG_SERVER_IMAGE}:${IMAGE_SUFFIX:-latest}${WEEKLY_BUILD_DATE:+-${WEEKLY_BUILD_DATE}}${WEEKLY_BUILD_DATE:+-weekly}
    hostname: aig-server
    container_name: aig-server
    read_only: true
    security_opt:
      - no-new-privileges
    build:
      context: $PWD/aig
      dockerfile: $PWD/aig/Dockerfile
      target: aig-server
      args:
        UID: ${UID} 
        USER: ${USER} 
        BASE_IMAGE: "ubuntu:22.04"
        no_proxy: ${no_proxy}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    privileged: false
    stdin_open: true
    restart: unless-stopped
    tty: true
    entrypoint: ["./run.sh"]
    networks: 
      - app_network
    environment:
      - no_proxy=${no_proxy},ase-chromadb,web-ui
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - HTTPS=false # Make it "true" to enable SSL/TLS secure mode, mount the generated certificates
      - REST_SERVER_PORT=${AIG_PORT}      
      - SERVICE_NAME=aig-server
      - ZE_ENABLE_ALT_DRIVERS=libze_intel_vpu.so
      - AIG_VERSION=${IMAGE_SUFFIX}
      - AIG_PORT=${AIG_PORT}
      - AIG_LOGO_PATH=${AIG_LOGO_PATH}
      - AIG_FONT_PATH=${AIG_FONT_PATH}
      - AIG_MODEL_PATH=${AIG_MODEL_PATH}
      - AIG_MODEL_DEVICE=${AIG_INFERENCE_DEVICE:-GPU} # Default Device to run the model on (e.g., CPU, GPU)
      - AIG_MODEL_NUM_INFERENCE_STEPS=${AIG_MODEL_NUM_INFERENCE_STEPS} # Number of inference steps for the model
      - AIG_IMG_WIDTH_DEFAULT=${AIG_IMG_WIDTH_DEFAULT} # Default image width for the model
      - AIG_IMG_HEIGHT_DEFAULT=${AIG_IMG_HEIGHT_DEFAULT} # Default image height for the model
      - LIBVA_DRIVER_NAME=iHD #OpenVINO & OneAPI
      - VIDEO_GROUP_ID=44 #OpenVINO & OneAPI
      - LD_LIBRARY_PATH="/usr/lib/wsl/lib" #WSL2 specific, it is needed to run the container in WSL2
      - ASE_COLLECTION_NAME=${ASE_COLLECTION_NAME} # Name of the ASE collection to use
      - ASE_CHROMADB_PORT=${ASE_CHROMADB_PORT} # Port for ChromaDB service      
      - ASE_CHROMADB_HOST=ase-chromadb # Hostname for ChromaDB service
      - ASE_IMG_PATH=${ASE_IMG_PATH} # Path in the container to save the model converted to OpenVINO format
      - ASE_MODEL_PATH=${ASE_MODEL_PATH}
      - ASE_IMG_DEFAULT_AD=${ASE_IMG_DEFAULT_AD} # Default image when no ads are available
      - ASE_ENABLE_SAMPLEDATA=${ASE_ENABLE_SAMPLEDATA} # Enable sample data for the ASE service
      - ASE_ENABLE_SAMPLEDATA_DIR=${ASE_ENABLE_SAMPLEDATA_DIR}
      - ASE_DISTANCE_MAX_THRESHOLD=${ASE_DISTANCE_MAX_THRESHOLD}
      - AIG_KEEP_MODEL_IN_MEMORY=${AIG_KEEP_MODEL_IN_MEMORY} # Whether to keep the model in memory after first use
      - OPENVINO_LOG_LEVEL=3 # OpenVINO log level (0-4, where 0 is the most verbose)
    depends_on:
      - ase-chromadb
    volumes:
      - vol_pipeline_root:/var/cache/pipeline_root:uid=${UID},gid=${UID}
      - vol_pipeline_root:/home/ubuntu/.cache
      - "/run/udev:/run/udev:ro"
      - "/dev/dri:/dev/dri"
      - "/tmp:/tmp"
      - ./aig/sharedata:/opt/sharedata
      - ./aig/src:/home/aigserver/src
      - ./aig/models:/opt/models
      - "/usr/lib/wsl:/usr/lib/wsl" #WSL2 specific, Mandatory if you run in WSL2 th container initialzation
    group_add:
      # render group ID for ubuntu 20.04 host OS
      - "109"
      # render group ID for ubuntu 22.04 host OS
      - "110"
      # render group ID for ubuntu 24.04 host OS
      - "992"
    device_cgroup_rules:
      # Default run - device-cgroup-rule='c 189:* rmw'
      # Selective rules can be applied for deployment
      - "c 189:* rmw"
      - "c 209:* rmw"
      - "a 189:* rwm"
    devices:
      # Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
       # accel - NPU
      # Selective mount can be done for deployment as mounting whole /dev is not recommended
      - "/dev/dri:/dev/dri"

  web-ui:
    image: ${DOCKER_REGISTRY}${WEB_UI_IMAGE}:${IMAGE_SUFFIX:-latest}${WEEKLY_BUILD_DATE:+-${WEEKLY_BUILD_DATE}}${WEEKLY_BUILD_DATE:+-weekly}
    hostname: web-ui
    container_name: web-ui
    read_only: true
    security_opt:
      - no-new-privileges
    build:
      context: $PWD/web-ui
      dockerfile: $PWD/web-ui/Dockerfile
      args:
        no_proxy: ${no_proxy}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        UID: ${UID} 
        USER: ${USER} 
    networks:
      - app_network
    environment:
      - no_proxy=${no_proxy},mediamtx,aig-server,mqtt-broker
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - TIME_TO_DISPLAY_AD_SECONDS=${TIME_TO_DISPLAY_AD_SECONDS}
      - OBJECT_RECENCY_FRAME_COUNT=${OBJECT_RECENCY_FRAME_COUNT}
      - OBJECT_CONFIDENCE_THRESHOLD=${OBJECT_CONFIDENCE_THRESHOLD}
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - AIG_INFERENCE_DEVICE=${AIG_INFERENCE_DEVICE:-GPU} # Default Device to run the model on (e.g., CPU, GPU)
    depends_on:
      - mediamtx
      - aig-server
    restart: unless-stopped
    volumes:
      - ./web-ui/ProductAssociations.csv:/app/ProductAssociations.csv:ro
      - ./web-ui/pre-defined-ads:/app/pre-defined-ads:ro
      - ./web-ui/context_rules.json:/app/context_rules.json:ro
  
  nginx:
    image: nginx:1.31.5
    container_name: nginx_proxy
    read_only: true
    user: "2999:2999" # Use a non-root user for security
    security_opt:
    - no-new-privileges
    restart: unless-stopped
    command: >
     /bin/sh -c "sh /usr/local/bin/nginx-cert-gen.sh && exec nginx -g 'daemon off;'"
    environment:
      no_proxy: "web-ui,mqtt-broker,coturn,mediamtx,${no_proxy},${HOST_IP},dlstreamer-pipeline-server, aig-server"
      NO_PROXY: "web-ui,mqtt-broker,coturn,mediamtx,${no_proxy},${HOST_IP},dlstreamer-pipeline-server, aig-server"
      MEDIAMTX_SERVER: mediamtx
      WHIP_SERVER_PORT: ${WHIP_SERVER_PORT}
    ports:
      - "5000:15443"   # HTTPS for Web-UI and AIG & DLSPS Rest API
    volumes:
      - ./configs/nginx/nginx.conf:/tmp/default.conf.template:ro
      - ./configs/nginx/nginx-cert-gen.sh:/usr/local/bin/nginx-cert-gen.sh:ro
      - vol_nginx_tmpfs:/opt/nginx/certs:rw
      - vol_nginx_tmpfs:/var/cache/nginx:rw
      - vol_nginx_tmpfs:/run:rw
      - vol_nginx_tmpfs:/etc/nginx/:rw
    networks:
      - app_network
    depends_on:
      - web-ui
      - mqtt-broker
      - mediamtx
      - coturn

  model-download:
    profiles: ["model-download"]
    image: ${MODEL_DOWNLOAD_IMAGE:-intel/model-download}:${MODEL_DOWNLOAD_IMAGE_SUFFIX:-${IMAGE_SUFFIX:-latest}}${WEEKLY_BUILD_DATE:+-${WEEKLY_BUILD_DATE}}${WEEKLY_BUILD_DATE:+-weekly}
    container_name: model-download
    group_add:
      - "${MODEL_DOWNLOAD_HOST_GID:-1000}"
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        sed -i \
          -e 's#https://raw.githubusercontent.com/open-edge-platform/dlstreamer/4d22f42ffe1df79800dc2ef1749f7e37f3d47bf1/samples#https://cdn.jsdelivr.net/gh/open-edge-platform/dlstreamer@4d22f42ffe1df79800dc2ef1749f7e37f3d47bf1/samples#g' \
          -e 's#https://raw.githubusercontent.com/openvinotoolkit/model_server/#https://cdn.jsdelivr.net/gh/openvinotoolkit/model_server@#g' \
          /opt/entrypoint.sh
        exec /opt/entrypoint.sh "$$@"
      - model-download-entrypoint
      - --plugins
      - ${MODEL_DOWNLOAD_PLUGINS:-huggingface,openvino,ultralytics}
    ports:
      - "127.0.0.1:${MODEL_DOWNLOAD_PORT:-8000}:8000"
    environment:
      HF_TOKEN: ${HF_TOKEN:-}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN:-}
      HF_HUB_ENABLE_HF_TRANSFER: "1"
      http_proxy: ${http_proxy:-}
      https_proxy: ${https_proxy:-}
      no_proxy: ${no_proxy:-}
      HTTP_PROXY: ${HTTP_PROXY:-${http_proxy:-}}
      HTTPS_PROXY: ${HTTPS_PROXY:-${https_proxy:-}}
      NO_PROXY: ${NO_PROXY:-${no_proxy:-}}
      SSL_CERT_FILE: /opt/host-ca/ca-certificates.crt
      CURL_CA_BUNDLE: /opt/host-ca/ca-certificates.crt
      REQUESTS_CA_BUNDLE: /opt/host-ca/ca-certificates.crt
    volumes:
      - ./configs/pid/models/object_detection:/opt/models/pid/object_detection
      - ./aig/models:/opt/models/aig/models
      - ${MODEL_DOWNLOAD_CA_BUNDLE:-/etc/ssl/certs/ca-certificates.crt}:/opt/host-ca/ca-certificates.crt:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  vol_pipeline_root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_nginx_tmpfs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  chroma_data:
